"""Generate Egyptian semantics from checksum-pinned Unicode 17.0.0 data."""
import argparse
import hashlib
from pathlib import Path
import re
from urllib.request import urlopen

VERSION = '17.0.0'
SOURCES = {
    'StandardizedVariants.txt': 'f55100b2fb11d3d75a37b8c1ab752192dbd1c4b12328c5ec6b38e3807c0ca597',
    'Unikemet.txt': 'a7b46c19e24355257030b73be046c71b172595ec4a106867d3f988e3a4007208',
}
ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'src/xsr/egyptian/unicode_data.py'


def generate(directory):
    data = {}
    for name, digest in SOURCES.items():
        path = directory / name
        if not path.exists():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(urlopen(f'https://www.unicode.org/Public/{VERSION}/ucd/{name}', timeout=60).read())
        raw = path.read_bytes()
        if hashlib.sha256(raw).hexdigest() != digest:
            raise ValueError(f'Unicode checksum mismatch: {name}')
        data[name] = raw.decode('utf-8')
    rotations = {}
    for line in data['StandardizedVariants.txt'].splitlines():
        match = re.match(r'([0-9A-F]+) ([0-9A-F]+); rotated (?:approximately )?(\d+) degrees', line)
        if match:
            base, vs, angle = match.groups()
            if 0x13000 <= int(base,16) <= 0x143FF:
                rotations[(int(base,16), int(vs,16))] = int(angle)
    restrictions = {'kEH_NoMirror': [], 'kEH_NoRotate': []}
    for line in data['Unikemet.txt'].splitlines():
        fields = line.split('\t')
        if len(fields)==3 and fields[1] in restrictions and fields[2]=='Y':
            restrictions[fields[1]].append(int(fields[0][2:],16))
    out = ['# Generated by scripts/generate_unicode_data.py; do not edit.',
           '# Derived from Unicode data; see unicode-LICENSE.txt alongside this module.',
           f'UNICODE_VERSION = {VERSION!r}', 'ROTATIONS = {']
    out += [f'    (0x{b:X}, 0x{v:X}): {a},' for (b,v),a in sorted(rotations.items())]
    out += ['}']
    for prop,name in [('kEH_NoMirror','NO_MIRROR'),('kEH_NoRotate','NO_ROTATE')]:
        out += [name+' = frozenset({', *[f'    0x{cp:X},' for cp in restrictions[prop]], '})']
    return '\n'.join(out)+'\n'


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source-dir',type=Path,default=ROOT/'tmp/unicode')
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    output=generate(args.source_dir)
    if args.check:
        if OUTPUT.read_text(encoding='utf-8')!=output:
            raise SystemExit('Generated Unicode data is stale')
    else:
        OUTPUT.write_text(output,encoding='utf-8',newline='\n')

if __name__=='__main__':
    main()
