"""Maintain the sole XSR software version source and the TeX-readable stamp."""
from __future__ import annotations

import argparse
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "VERSION"
TARGET = ROOT / "tex" / "xsr-version.tex"


def expected_stamp() -> str:
    version = SOURCE.read_text(encoding="utf-8").strip()
    if not re.fullmatch(r"(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*)){1,2}", version):
        raise ValueError(f"invalid XSR software version: {version!r}")
    return (
        "% Generated by scripts/sync_version.py from VERSION; do not edit.\n"
        + r"\def\xsrPackageVersion{" + version + "}\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the generated TeX stamp is stale")
    args = parser.parse_args()
    generated = expected_stamp()
    if args.check:
        if not TARGET.is_file() or TARGET.read_text(encoding="utf-8") != generated:
            parser.error("TeX version stamp differs from VERSION; run python scripts/sync_version.py")
    else:
        TARGET.write_text(generated, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
